"""add constraint

Revision ID: 6f68791a190c
Revises: bf316295958f
Create Date: 2026-01-17 17:17:38.800786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f68791a190c'
down_revision: Union[str, Sequence[str], None] = 'bf316295958f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bookmarks', ['user_id', 'article_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookmarks', type_='unique')
    # ### end Alembic commands ###
